# 配置服务端口
server:
  port: 8082

spring:
# 配置应用名称
  application:
    name: JavaWeb_Framework

# 配置数据库
  datasource:
    # 数据库连接池
    #url: jdbc:mysql://localhost:3306/mybatisplus-frame-test?serverTimezone=UTC
    url: jdbc:p6spy:mysql://localhost:3306/mybatisplus-frame-test?serverTimezone=UTC

    # 数据库驱动
    # driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

    # 数据库用户名与密码
    username: 'root'
    password: 'nm2295761'

# MyBatis Plus配置
# 关闭在控制台打印LOGO
mybatis-plus:
  global-config:
    banner: false

# P6Spy配置
logging:
  level:
    com:
      p6spy: INFO